<font face="Courier New">

# numpy 基础

In [1]:
import numpy as np

## 排序和索引

In [2]:
x = np.arange(6, 22)

### 一. 将 x 进行乱序处理

In [3]:
np.random.shuffle(x)
print(x)

[ 9 19 14 10 21 11  8 16 15 18  7  6 13 17 12 20]


### 二. 将 x 进行顺序处理

#### 2.1 方法一: 不修改原数据

In [4]:
sortX = np.sort(x)
print(sortX)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


#### 2.2 方法二: 修改原数据

In [5]:
# x.sort()
# print(x)

#### 2.3 行方向排序 `axis = 1` (默认)

In [6]:
m = np.random.randint(10, size=(4, 4))
sortM1 = np.sort(m)

#### 2.4 列方向排序 `axis = 0`

In [7]:
sortM0 = np.sort(m, axis=0)

#### 2.5 返回排序后对应数据的索引值

In [8]:
np.argsort(x)

array([11, 10,  6,  0,  3,  5, 14, 12,  2,  8,  7, 13,  9,  1, 15,  4])

#### 2.6 定点排序

In [9]:
np.partition(x, 5)  # 索引为5的位置, 前面的数字比它小, 后面的数字比它大

array([ 6,  7,  9,  8, 10, 11, 12, 13, 15, 14, 16, 18, 19, 17, 21, 20])

## 三. 索引

<font face="Courier New">
    
## 3.1 一维矩阵的索引

In [10]:
x = np.arange(5, 25)
print(x)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<font face="Courier New">
    
### 3.1.1 指定区间及步长索引

In [11]:
x[3:9:2] # 从下标为 3 的位置开始索引, 步长为 2 取值

array([ 8, 10, 12])

In [12]:
x[:3]

array([5, 6, 7])

<font face="Courier New">
    
### 3.1.2 根据下标直接索引

In [13]:
[x[3], x[5], x[7]]

[8, 10, 12]

<font face="Courier New">
    
### 3.1.3 根据表达式索引

In [14]:
x[x < 10]

array([5, 6, 7, 8, 9])

In [15]:
x[x % 2 == 0]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

### 3.2 二维矩阵索引

In [16]:
xx = np.arange(16).reshape(4, 4)
xx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
xx[:, :]  # xx[:, :] 与 xx[0:4, 0:4] 含义相同

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
xx[1:3, :]  # 行取:1-3, 列 ':' 表示全取 而且可以省略

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
xx[0:4, -3:-1]  # 行取:0-4, 列取:-3~-1

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [20]:
xx[0:4:2, -3:-1]  # 行按步长2取:0-4的区间, 列取:-3~-1

array([[ 1,  2],
       [ 9, 10]])

In [21]:
xx[::2, -3:-1]  # 与上面相同的意思

array([[ 1,  2],
       [ 9, 10]])

In [22]:
print(xx)
xx[:, -1:]    # 每一行都取, 列从-1取值到最后

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 3],
       [ 7],
       [11],
       [15]])

In [23]:
print(xx)
xx[:, -1]  # 每一行都取, 列取-1 (注意与上面的不同之处)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 3,  7, 11, 15])

In [24]:
print(xx)
xx[xx[:, -1] % 3 == 0, :] # 取出每一行末尾数字可以被三整除的行

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### 3.3 三维矩阵索引

In [25]:
np3 = np.array([[[1, 2, 13], [3, 4, 14]], [[5, 6, 15], [7, 8, 16]], [[9, 10, 17], [11, 12, 18]]])
np3

array([[[ 1,  2, 13],
        [ 3,  4, 14]],

       [[ 5,  6, 15],
        [ 7,  8, 16]],

       [[ 9, 10, 17],
        [11, 12, 18]]])

In [26]:
np3[2, 1, -2]

12

In [27]:
np3[0:2]

array([[[ 1,  2, 13],
        [ 3,  4, 14]],

       [[ 5,  6, 15],
        [ 7,  8, 16]]])

In [28]:
np3[0:2, 0:1]

array([[[ 1,  2, 13]],

       [[ 5,  6, 15]]])

In [29]:
np3[0:2, 0:1, -2:]

array([[[ 2, 13]],

       [[ 6, 15]]])

In [30]:
np3[:,:,-1:]

array([[[13],
        [14]],

       [[15],
        [16]],

       [[17],
        [18]]])

<font face="Courier New">
    
### 3.4 根据 list 索引(注意:list内的数字不能大于矩阵的最大索引)

In [31]:
indx = [3, 5, 8]
print(x[indx])

[ 8 10 13]


<font face="Courier New">

### 3.5 根据 `np.array` 矩阵索引

In [32]:
indx = np.array([[1, 3], [2, 4]])
print(x[indx])

[[6 8]
 [7 9]]


<font face="Courier New">
    
#### 将 x 转成 4*5 的矩阵

In [33]:
reX = x.reshape(4, 5)
print(reX)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


<font face="Courier New">

### 3.6 根据 行列矩阵 索引

In [34]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 4])

<font face="Courier New">
    
#### 3.6.1 取出(0, 1) (1, 2) (2, 4) 三个点

In [35]:
print(reX)
reX[row, col]

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 6, 12, 19])

<font face="Courier New">
    
#### 3.6.2 取出第 0 行的(0, 1) (0, 2) (0, 4)三个点

In [36]:
print(reX)
reX[0, col]

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([6, 7, 9])

<font face="Courier New">
    
#### 3.6.3 取出前两行对应的(x, 1) (x, 2) (x, 4)六个点 x 为0, 1

In [37]:
print(reX)
reX[:2, col]

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7,  9],
       [11, 12, 14]])

<font face="Courier New">
    
#### 3.6.4 此处定义 bool 列表, 表示对第 0, 2, 4 列感兴趣, 排除 1, 3 列

In [38]:
col = [True, False, True, False, True]

In [39]:
print(reX)
reX[:, col]  # 针对所有行

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [40]:
reX[3:4, col]  # 3-4行的区间内

array([[20, 22, 24]])

## 四. 表达式

<font face="Courier New">
    
### 4.1 `numpy.array` 表达式比较之后返回 bool 值

In [41]:
print(reX)
result = reX < 7 # 返回比较后的 bool 值
result

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

### 4.2 取出满足条件: `x3 < 7` 相应的数字

In [42]:
reX[result]

array([5, 6])

<font face="Courier New">
    
### 4.3 矩阵中的数字满足条件表达式返回 True, 不满足返回 False

In [43]:
# x3 的值 5 时满足此等式, x3 中第一个元素为5, 因此为 True , 其余为 False
2 * reX == 20 - 2 * reX

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

<font face="Courier New">
    
### 4.4 `np.sum()` 求矩阵中满足条件的数字总个数

In [44]:
print(reX)
np.sum(reX <= 10) # x3 中有6个小于等于10的数字

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6

In [45]:
np.sum((reX > 8) & (reX < 12)) # 满足 x > 8 并且 x < 12 的数字

3

In [46]:
# 假如 x 满足 x > 8 并且 x < 12 的数字
np.sum((reX > 8) & (reX < 12), axis=1) 

array([1, 2, 0, 0])

<font face="Courier New">

### 4.5 `np.count_nonzero()` 判断矩阵中存在多个满足条件的非零数字

In [47]:
np.count_nonzero(reX <= 10) # x3 中有6个小于等于10的非零数字

6

<font face="Courier New">
    
### 4.6 `np.any()`

In [48]:
np.any(reX == 0)  # 如果 x3 中有数字0, 结果为True, 如果没有0, 结果为False

False

In [49]:
np.any(reX > 0)  # x3 中的元素存在大于0数字

True

<font face="Courier New">
    
### 4.7 `np.all()`

In [50]:
print(reX)
np.all(reX > 10)  # 如果 x3 中所有的数字都大于10, 返回True, 否则返回False

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


False

In [51]:
np.all(reX > 10, axis=1)

array([False, False,  True,  True])

### 4.8 判断矩阵中有多少个偶数

In [52]:
print(reX)
np.sum(reX % 2 == 0)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


10

### 4.9 判断矩阵中有多少个偶数(指定维度)

In [53]:
X = np.arange(16).reshape(4,4)

In [54]:
print(X)
np.sum(X % 2 == 0, axis=0)  # 每一列有多少偶数

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([4, 0, 4, 0])

In [55]:
print(X)
np.sum(X % 2 == 0, axis=1)  # 每一行有多少个偶数

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([2, 2, 2, 2])

### 4.10 与或非运算

In [56]:
print(X)
np.sum((X > 2) & (X < 10))  # X 中即大于2 又小于10的个数
np.sum((X % 2 == 0) & (X < 10))  # X 中小于10的偶数有多少个

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


5

In [57]:
np.sum((X > 15) | (X < 10))  # X 中小于10 或者X 大于15 有多少个

10

In [58]:
np.sum(~(X == 0))  # X 中有多少个非零的数字

15